apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-helm
  namespace: argocd
spec:
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-v2